Expand the Directory Instructions Template
freedomofpress/securedrop.org pull request #1010
Opened 2023-03-16 18:45 UTC by nathandyer

This PR expands the directory instructions to provide some additional clarity to potential sources.

The primary change is that it makes it clear that seeing a different onion address in the URL bar inside of Tor Browser for securedrop.org does not constitute an onion address mismatch with an organization's Source Interface.

It also provides some slight tweaks to make the workflow a bit clearer.

If possible, I would appreciate @eloquence's review of the content, in addition to the standard review procedure by the web team. Thanks!

2023-04-18 21:50 UTC, eloquence requested changes
Thanks for your work on this, Nathan! Here's what this change looks like when I build it locally:

![image](https://user-images.githubusercontent.com/213636/232912584-7d852b3a-1537-4a69-a8af-a66aad960e86.png)

Compared with the current version:

![image](https://user-images.githubusercontent.com/213636/232912694-58ed7e48-3fb5-4480-9398-f3ac47a7dace.png)

I think we have a bit of a verbosity issue (even in the old version), which can lead to folks just glancing over the instructions and missing the most essential bits.

I'll put together a GDoc where we can workshop this a bit together before revising the PR.

2023-04-18 21:54 UTC, eloquence commented on directory/templates/directory/_instance_instructions.html
> +			using the Tor Browser.
My understanding is that Tor Browser, by default, only shows the .onion as ".onion available" - you can turn on a preference to automatically go to the .onion.

2023-04-18 22:01 UTC, eloquence commented
I've started [this doc](https://docs.google.com/document/d/1C4n5UeW_eQRVc0wnUUrVJGLPQfkrqUm8PwsNLfp1YTo/edit) to workshop the instructions further :)

2023-04-19 15:12 UTC, nathandyer commented
Thank you for putting together that doc so we can workshop the instructions, @eloquence! I agree that both the original and modified text here in the PR is too verbose, and really like the changes you've put together so far. I made one suggested tweak to try and capture the nuance about the .onion address mismatches (clarifying to be on the lookout for the ones on the landing page and comparing them to the ones listed in the directory guide). Please feel free to tweak that further or make an alternate suggestion. Otherwise, I'm in favor of what you have put together so far, and will be glad to update the PR accordingly.

2023-04-21 15:37 UTC, nathandyer commented
I updated this PR with the latest text from our workshopped version. I was a bit unsure about the logic related to the GPG email preferences, so if I need to make tweaks with that (or any of it), please let me know. Thanks!

2024-01-04 22:31 UTC, eloquence commented on directory/templates/directory/_instance_instructions.html
> +			If the .onion address information on {{ organization }}’s web page
Suggestion after seeing it in context: Maybe we should use "landing page" instead of "web page" here since we're using in the link description and the warning copy. (It's our internal jargon, so I almost would prefer to get rid of it completely, but if we're using it, using it consistently may help with pattern-matching.)

2024-01-04 22:35 UTC, eloquence approved these changes

2024-01-04 22:36 UTC, eloquence commented
Left one suggestion but wording looks good from my end either way! Leaving for web team to merge in case I'm missing anything, but I don't see an issue with the logic -- the basic idea is that if a page like https://securedrop.org/report-an-error/ is configured (which it is in prod), we'll link to that instead of the email address.

2024-01-08 15:11 UTC, nathandyer commented on directory/templates/directory/_instance_instructions.html
> +			If the .onion address information on {{ organization }}’s web page
Thanks @eloquence, I agree - I've updated this to use the term "landing page" instead.

2024-04-09 23:58 UTC, eloquence commented
Rebased; flagged to SD team in case of any concerns about language update, so keeping "in progress" for now.

2024-04-10 17:34 UTC, eloquence commented
3 thumbs-ups from SD team members so I think this is good for a quick final pass from @freedomofpress/fpf-web-developers  :)

2024-04-10 18:22 UTC, chigby approved these changes
Everything seems to look good from my perspective.

2024-04-10 19:47 UTC, merged