Update wagtail 6.3
freedomofpress/securedrop.org pull request #1161
Opened 2024-12-30 17:27 UTC by SaptakS

## Description

Fixes #1158 .

Changes proposed in this pull request:
- Updates Wagtail to 6.3 (LTS) and other necessary packages
- Updates createdevdata code to use fixtures and local images for the admin.

## Type of change

- [ ] Bug fix
- [ ] New feature
- [x] Version update
- [ ] Config changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires an admin update after deploy
- [ ] Includes a database migration removing  or renaming a field

## Testing

How should the reviewer test this PR?
Check that everything works without anything being broken.

2025-01-06 21:57 UTC, chigby requested changes
I think this overall update is great. There's one small change I would add:

The release notes for wagtail 6.0 mention [the Copy view being enabled by default](https://docs.wagtail.org/en/stable/releases/6.0.html#snippetviewset-modelviewset-copy-view-enabled-by-default). I think it's worth adding `copy_view_enabled = False` to `ScanResultAdmin` to avoid having the (broken) "Copy" action show up on the scan result list, as shown below.

<img width="664" alt="image" src="https://github.com/user-attachments/assets/f795bb1f-ffdc-42c8-b29c-5ba2cddb26c6" />

2025-01-06 21:57 UTC, chigby commented on requirements.txt
> +wagtail==6.3.1 \
We might as well make this wagtail 6.3.2, which [is now released](https://docs.wagtail.org/en/stable/releases/6.3.2.html).

2025-01-06 21:57 UTC, chigby commented on common/management/commands/createdevdata.py
> +        print(file_names)
Cleanup: print calls can be removed.

2025-01-06 21:57 UTC, chigby commented on common/management/commands/createdevdata.py
> +        print(CustomImage.objects.all())
Cleanup: print call can be removed.

2025-01-07 16:33 UTC, SaptakS commented
@chigby addressed your comments.

2025-01-07 17:09 UTC, chigby commented
@SaptakS Did you see the mention of wagtail 6.3.2?

2025-01-07 17:12 UTC, SaptakS commented
Aah yes. Missed that.

2025-01-07 22:04 UTC, chigby approved these changes

2025-01-07 22:04 UTC, merged