Display a more clear message when Instance is down for Maintenance
freedomofpress/securedrop.org pull request #715
Opened 2020-08-06 09:58 UTC by prateekj117

Fixes #700 

The old instance alert message language was problematic and misguiding when the instance is simply down for maintenance. So it is better if we add a separate message if the instance is simply down for maintenance.

2020-08-18 16:44 UTC, prateekj117 commented
@eloquence Ready for review.

2020-08-20 14:30 UTC, SaptakS requested changes
@prateekj117 looks almost ready to be merged! The migration file is missing from the PR. Please add the corresponding migration file related to the change in [DELISTED_REASONS](https://github.com/freedomofpress/securedrop.org/pull/715/files#diff-60b040892be58a6c734077904ce23effR170)

2020-08-20 14:30 UTC, SaptakS commented on directory/templates/directory/_instance_maintenance_alert.html
> +</div>
Nitpicking, please add a line at the end of file.

2020-08-20 15:36 UTC, prateekj117 commented
@SaptakS Ready for another review.

2020-08-24 13:24 UTC, SaptakS approved these changes
Looks good to me

2020-08-25 09:58 UTC, prateekj117 commented
@harrislapiroff Ready for review.

2020-09-02 16:21 UTC, merged