Adds a skip link to every page and adds context for links
freedomofpress/securedrop.org pull request #895
Opened 2021-09-20 14:31 UTC by SaptakS

Fixes #873 
Fixes #872 

This PR adds a "Skip to content" link to every page that takes the user directly to the page-title of the page. The link is not visible unless someone uses tab to navigate and focuses on that link (which is always the very first link in the page). This is how it looks when focused:
![Screenshot from 2021-09-20 19-58-57](https://user-images.githubusercontent.com/9530293/134020073-b48d32cb-cda9-4251-a2e7-de76742c3f89.png)

Also, in this PR, I have added aria-label to links which have generic text like "Read more", "View in directory" to add more context. It doesn't change any visuals, but gives more context to screen reader and other assistive tech users.

2021-09-20 19:12 UTC, harrislapiroff requested changes
Design changes look fine, but one minor comment on one of the other accessibility changes. Looks really great otherwise!

2021-09-20 19:12 UTC, harrislapiroff commented on marketing/templates/marketing/_features_list.html
> +			<a class="features-list__item" href="{% pageurl feature.feature %}" arial-label="{% trans 'Know more about the feature: ' %}{{ feature.feature.teaser_title }}">
Do I understand correctly that aria-label prevents text inside the element from being read? I don't think we actually want that here since the text is meaningful.

2021-09-20 20:33 UTC, SaptakS commented on marketing/templates/marketing/_features_list.html
> +			<a class="features-list__item" href="{% pageurl feature.feature %}" arial-label="{% trans 'Know more about the feature: ' %}{{ feature.feature.teaser_title }}">
@harrislapiroff that is correct. This is what the screen reader reads out:

![Screenshot 2021-09-21 at 1 44 50 AM](https://user-images.githubusercontent.com/9530293/134071609-c64e7c75-1add-4c6f-8807-4f7ddc818eda.jpg)

If that looks good to you, can remove aria-label from this.

2021-09-21 15:19 UTC, harrislapiroff commented on marketing/templates/marketing/_features_list.html
> +			<a class="features-list__item" href="{% pageurl feature.feature %}" arial-label="{% trans 'Know more about the feature: ' %}{{ feature.feature.teaser_title }}">
Yeah, I think that's preferable to the label. You could mark the image as presentation imo, but I'll leave it up to you how much detail screenreader users want. With that fixed, this PR is good to go! I'll approve it provisionally.

2021-09-21 15:20 UTC, harrislapiroff approved these changes

2021-09-21 16:47 UTC, SaptakS commented
Weird that the build failed in this PR 🤔

2021-09-22 14:40 UTC, harrislapiroff commented
I wonder if it's a pipenv change. I think we do install the latest on every CI run. I'll rerun to see.

2021-09-22 14:40 UTC, harrislapiroff commented
Er, I guess it would be pip not pipenv

2021-09-22 16:03 UTC, SaptakS commented
@chigby @harrislapiroff passing now!

2021-09-24 10:20 UTC, merged